### ISSUE TITLE
Why use the private IP address?

### ISSUE THREAD

**Issue by Miciah** [istib/helm-aws#9]
Is there a reason `aws-get-ip-from-instance` returns the private address instead of the public address? My use case for `helm-aws` is interacting with EC2 instances from my local machine.  Is `helm-aws` designed for a different use case where the public address would not exist or would not be appropriate?

If using the private address is necessary for some use case, I propose adding a user option, for example a Boolean named `helm-aws-use-private-addresses`, to provide users the choice.

If there is no use case that requires private addresses, I propose changing `aws-get-ip-from-instance` to use `:PublicIpAddress` instead of `:PrivateIpAddress` (which is what I have done already with my private version of `helm-aws`).

I am happy to make a PR for either one of these options if it would be accepted.

**Comment by istib** [comment]
Good idea, I would merge a PR that implements this. Many thanks !
